"""Initial schema

Revision ID: 15cfa1a8cdc3
Revises: 
Create Date: 2025-11-12 23:54:53.315171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15cfa1a8cdc3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=128), nullable=True),
    sa.Column('telegram_start_token', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_start_token'),
    sa.UniqueConstraint('username')
    )
    op.create_table('search_preferences',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('query_params', sa.JSON(), nullable=False),
    sa.Column('check_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_preferences_user_id'), 'search_preferences', ['user_id'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('preference_id', sa.String(length=64), nullable=False),
    sa.Column('listing_id', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('price', sa.String(length=64), nullable=True),
    sa.Column('price_hash', sa.String(length=64), nullable=True),
    sa.Column('price_drop_notified', sa.Boolean(), nullable=False),
    sa.Column('last_notification_type', sa.String(length=32), nullable=True),
    sa.Column('last_notified_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['preference_id'], ['search_preferences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listing_preference_listing', 'listings', ['preference_id', 'listing_id'], unique=False)
    op.create_index('ix_listing_user_listing', 'listings', ['user_id', 'listing_id'], unique=True)
    op.create_index(op.f('ix_listings_preference_id'), 'listings', ['preference_id'], unique=False)
    op.create_index(op.f('ix_listings_user_id'), 'listings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_user_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_preference_id'), table_name='listings')
    op.drop_index('ix_listing_user_listing', table_name='listings')
    op.drop_index('ix_listing_preference_listing', table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_search_preferences_user_id'), table_name='search_preferences')
    op.drop_table('search_preferences')
    op.drop_table('users')
    # ### end Alembic commands ###
